### ISSUE TITLE
Error message when installing the extension using Chocolatey

### ISSUE THREAD

**Issue by kcswe** [chocolatey-community/chocolatey-vscode#155]
Error message when installing the extension using Chocolatey
## Expected Behavior

No error messages when installing

## Current Behavior

Error message like below:
(node:13596) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

## Steps to Reproduce (for bugs)

1. Open Powershell
2. Execute: choco install chocolatey-vscode -yes
3.
4.

## Your Environment

* Module version used:
* Operating System and PowerShell version: Windows 10

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  316
![image](https://user-images.githubusercontent.com/30314198/53907920-7b31d180-404e-11e9-9926-58f574357639.png)

**Comment by steviecoaster** [comment]
I believe this is probably coming from Visual Studio itself, and is related to NPM? @gep13 can you confirm my theory?

**Comment by AdmiringWorm** [comment]
This is indeed from vscode itself.

They seems to have the issue tracked here: https://github.com/Microsoft/vscode/issues/67534

**Comment by JPRuskin** [comment]
It looks like the linked issue has been closed off - I'll try replicating this today, and if it doesn't happen we can probably close this issue.

**Comment by JPRuskin** [comment]
Hm. Looks like it's still happening, here:

![image](https://user-images.githubusercontent.com/1975761/161236896-f64a51f0-e5ea-497e-9184-28b90dca37a7.png)

**Comment by corbob** [comment]
This is a vscode issue: https://github.com/microsoft/vscode/issues/82524

**Comment by corbob** [comment]
Looks like this was resolved by Microsoft in a release of VS Code.
